name: 'Common golang ci'
inputs:
  GH_TOKEN:
    description: "The GitHub token"
    required: true
  go-version:
    description: "The version of node to use"
    required: false
    type: string
    default: "latest"
outputs:
  new-release-published:
    description: "If a new release was published"
    value: ${{ steps.get-next-version.outputs.new-release-published }}
  new-release-version:
    description: "The version of the new release"
    value: ${{ steps.get-next-version.outputs.new-release-version }}

runs:
  using: "composite"
  steps:
    - uses: meza/action-go-setup@main
      name: 🔧 Set up Node.js
      with:
        go-version: ${{ inputs.go-version }}

    - name: 🔍 Test with the Go CLI
      uses: meza/action-go-test@main

    - uses: meza/action-do-semantic-release@main
      id: get-next-version
      with:
        GH_TOKEN: ${{ inputs.GH_TOKEN }}
        DryRun: 'true'
